import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "TBC React Accelerator",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params: { locale } }) {
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <div className="bg-white dark:bg-primary text-primary dark:text-white min-h-screen flex flex-col justify-between">
          {children}
        </div>
      </body>
    </html>
  );
}
